---
title: "" 
toc: false 
format:
  html: 
    grid:
      body-width: 950px
about: 
  template: marquee
  image-width: 20em
  links:
    - icon: mastodon
      text: Mastodon
      href: https://social.tchncs.de/@thhaase
    - icon: github
      text: Github
      href: https://github.com/thhaase
    - icon: envelope
      text: E-Mail
      href: "mailto:thhaase.soz@gmail.com"
    - icon: twitter
      text: Twitter/ X
      href: https://twitter.com/thhaase_
    - icon: spotify
      text: Spotify
      href: https://open.spotify.com/user/kvqz88xd4goy62kojjy507veu?si=KR6CHMmaTPmgJR3d1UdKHA
---

[Thomas Haase]{.orange-h1}

::: {.callout-note}
This is my "professional" aboutpage (atleast as it can get). <br>
For insights into my personal life/projects please visit the rest of this website.
:::

I am a BA social science student at [Justus-Liebig-University Gießen](https://www.uni-giessen.de/de/fbz/fb03) and also serve as a tutor for empirical methods and statistics.

[Experience]{.orange-h2}

- Tutor: 
    - Empirical methods & data collection procedures 
    - Statistics
- Student assistent for organizing a research and network conference with around 50 participants of the BMBF funding programm [International Humanities and Social Sciences](https://www.geistes-und-sozialwissenschaften-bmbf.de/en/International-Humanities-and-Social-Sciences-1696.html) 
- Internship [6weeks] @GESIS Computational Social Science <br>[main supervision by Judith Gilsbach and Dr. Sebastian Stier]{.small-grey-text}
---
- Workshop: Quantitative content analysis [8h] <br> [(Methodentage JLU 2023 - Dr. Marius Sältzer) ]{.small-grey-text}
- Workshop: Intro to multilevel analysis [16h] <br> [(Methodentage JLU 2022 - Sandra Scheuring)   ]{.small-grey-text}
- Workshop: Intro to SEM                 [16h] <br> [(Methodentage JLU 2022 - Dr. Henrik Andersen)]{.small-grey-text}

[Skills]{.orange-h2}

|          |                      |
|--------- |----------------------|
|          |                      |
| Basics   | R, Git(-hub), Linux  |
| Advanced | LaTeX                |

[Education]{.orange-h2}

|                   |                                                                                                |
|------------------ |------------------------------------------------------------------------------------------------|
| since 10/2021     | B.A. Sozialwissenschaften, Justus-Liebig-Universität, Gießen                                   |
| 2020 - 2021       | Physik, Justus-Liebig-Universität, Gießen <br> [Not completed - subsequent change of subject]{.small-grey-text} |

[Interests]{.orange-h2}

| R | Statistics | Computational Sociology | General Sociological Theory |

<!--
# what I do in my freetime
- R Workshops
- learning R and statistics
- linux, software and open source
- sorting my obsidean notes
-->



